# ChatSphere 数据库服务测试
version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: chatsphere-postgres-dbtest
    environment:
      POSTGRES_DB: chatsphere_dev
      POSTGRES_USER: chatsphere
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dbtest_data:/var/lib/postgresql/data
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatsphere -d chatsphere_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - chatsphere-dbtest

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: chatsphere-redis-dbtest
    command: redis-server --appendonly yes --requirepass dev_redis_123
    ports:
      - "6379:6379"
    volumes:
      - redis_dbtest_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "dev_redis_123", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - chatsphere-dbtest

# 数据卷
volumes:
  postgres_dbtest_data:
    driver: local
  redis_dbtest_data:
    driver: local

# 网络
networks:
  chatsphere-dbtest:
    driver: bridge
    name: chatsphere-dbtest-network
